fix mac bundle problems by copying fixPackage from openrpt and changing bundle.sh to use it (it would have been better to rm fixPackage entirely and copy it from openrpt when needed)

diff --git a/csvimp/trunk/fixPackage b/csvimp/trunk/fixPackage
--- a/csvimp/trunk/fixPackage
+++ b/csvimp/trunk/fixPackage
@@ -1,96 +1,188 @@
-#
-# This file is part of the xTuple ERP: PostBooks Edition, a free and
-# open source Enterprise Resource Planning software suite,
-# Copyright (c) 1999-2009 by OpenMFG LLC, d/b/a xTuple.
-# It is licensed to you under the Common Public Attribution License
-# version 1.0, the full text of which (including xTuple-specific Exhibits)
-# is available at www.xtuple.com/CPAL.  By using this software, you agree
-# to be bound by its terms.
-#
 #!/bin/bash
+PROG=`basename $0`
+INCLASSISTANT=false
+INCLDBPLUGINS=false
+INCLIMAGEPLUGINS=false
+INCLXTUPLEPLUGINS=false
 
-if [ -z "$QTDIR" ] ; then
-  QTDIR=/usr/local/Trolltech/Qt-4.2.3
+if ! [ -d $QTDIR ]; then
+  for PATHPART in `echo $PATH | tr : " "` ; do
+    if [ -f "$PATHPART"/qmake ] ; then
+      QTDIR="$PATHPART"
+    fi
+  done
 fi
-if ! [ -d $QTDIR ] ; then
-  echo "Canot find QTDIR"
-  exit
+if ! [ -d $QTDIR ]; then
+  echo "Cannot find QTDIR"
+  exit 1
 fi
 
-if [ -z "$PGDIR" ] ; then
-  PGDIR=$QTDIR
+if ! [ -d $PGDIR ]; then
+  for PATHPART in `echo $PATH | tr : " "` ; do
+    if [ -f "$PATHPART"/psql ] ; then
+      PGDIR="$PATHPART"
+    fi
+  done
 fi
-if ! [ -d $PGDIR/lib ] ; then
+if ! [ -d $PGDIR/lib ]; then
   echo "Cannot find PGDIR/lib"
-  exit
+  exit 1
 fi
 
-FRAMEWORKSDIR=csvimp.app/Contents/Frameworks
-if ! [ -d "$FRAMEWORKSDIR" ] ; then
-  mkdir $FRAMEWORKSDIR
+usage() {
+  echo "$PROG [ -h ] [ -a ] [ -p{IDX} ] .../executable.app [ executable-name ]"
+  echo
+  echo "-h      get this usage information"
+  echo "-a      include Qt Assistant as part of the application bundle"
+  echo "-p      include Qt Plugins as part of the application bundle"
+  echo "        I => include image plugins    [ $INCLIMAGEPLUGINS ]"
+  echo "        D => include database plugins [ $INCLDBPLUGINS ]"
+  echo "        X => include xTuple plugins   [ $INCLXTUPLEPLUGINS ]"
+  echo "-x      turn on shell debugging output"
+  echo
+  echo "The executable.app argument is the path of the Macintosh application"
+  echo "bundle directory. This can be either absolute or relative."
+  echo
+  echo "On rare occasion the executable file within the bundle has a different"
+  echo "name than the bundle itself. In this case, add the second executable-name"
+  echo "argument to specify the executable file."
+  echo
+  echo "Env variables:"
+  echo "QTDIR   location of Qt installation [ $QTDIR ]"
+  echo "PGDIR   location of PostgreSQL installation [ $PGDIR ]"
+  echo
+  echo "Examples:"
+  echo "$PROG ../bin/openrpt.app"
+  echo "$PROG /Users/random-user/testing.app trial"
+  echo "$PROG -a xtuple/trunk/bin/xtuple.app"
+}
+
+set -- `getopt hap:x $*`
+if [ $? != 0 ] ; then
+  usage
+  exit 1
 fi
-cd $FRAMEWORKSDIR
 
-cp $QTDIR/lib/libQt3Support.4.dylib \
-	      $QTDIR/lib/libQtNetwork.4.dylib \
-	      $QTDIR/lib/libQtSql.4.dylib 	 \
-	      $QTDIR/lib/libQtXml.4.dylib 	 \
-	      $QTDIR/lib/libQtGui.4.dylib 	 \
-	      $QTDIR/lib/libQtCore.4.dylib 	 \
-	      $PGDIR/lib/libpq.4.dylib	 .
+while [ $1 != -- ] ; do
+  case "$1" in
+    -h) usage
+        exit 0
+        ;;
+    -a) INCLASSISTANT=true
+        ;;
+    -p) if echo $2 | grep -q D ; then INCLDBPLUGINS=true     ; fi
+        if echo $2 | grep -q I ; then INCLIMAGEPLUGINS=true  ; fi
+        if echo $2 | grep -q X ; then INCLXTUPLEPLUGINS=true ; fi
+        shift
+        ;;
+    -x) set -x
+        ;;
+     *) usage
+        exit 1
+        ;;
+  esac
+  shift
+done
+shift # past the --
 
-install_name_tool -id @executable_path/../Frameworks/libpq.4.dylib libpq.4.dylib
-
-install_name_tool -id @executable_path/../Frameworks/libQt3Support.4.dylib libQt3Support.4.dylib
-install_name_tool -change $QTDIR/lib/libQtSql.4.dylib @executable_path/../Frameworks/libQtSql.4.dylib libQt3Support.4.dylib
-install_name_tool -change $QTDIR/lib/libQtXml.4.dylib @executable_path/../Frameworks/libQtXml.4.dylib libQt3Support.4.dylib
-install_name_tool -change $QTDIR/lib/libQtGui.4.dylib @executable_path/../Frameworks/libQtGui.4.dylib libQt3Support.4.dylib
-install_name_tool -change $QTDIR/lib/libQtNetwork.4.dylib @executable_path/../Frameworks/libQtNetwork.4.dylib libQt3Support.4.dylib
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libQt3Support.4.dylib
-
-install_name_tool -id @executable_path/../Frameworks/libQtNetwork.4.dylib libQtNetwork.4.dylib
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libQtNetwork.4.dylib
-
-install_name_tool -id @executable_path/../Frameworks/libQtSql.4.dylib libQtSql.4.dylib
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libQtSql.4.dylib
-
-install_name_tool -id @executable_path/../Frameworks/libQtXml.4.dylib libQtXml.4.dylib
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libQtXml.4.dylib
-
-install_name_tool -id @executable_path/../Frameworks/libQtGui.4.dylib libQtGui.4.dylib
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libQtGui.4.dylib
-
-install_name_tool -id @executable_path/../Frameworks/libQtCore.4.dylib libQtCore.4.dylib
-
-cd ../MacOS
-install_name_tool -change $QTDIR/lib/libQt3Support.4.dylib @executable_path/../Frameworks/libQt3Support.4.dylib csvimp
-install_name_tool -change $QTDIR/lib/libQtNetwork.4.dylib @executable_path/../Frameworks/libQtNetwork.4.dylib csvimp
-install_name_tool -change $QTDIR/lib/libQtSql.4.dylib @executable_path/../Frameworks/libQtSql.4.dylib csvimp
-install_name_tool -change $QTDIR/lib/libQtXml.4.dylib @executable_path/../Frameworks/libQtXml.4.dylib csvimp
-install_name_tool -change $QTDIR/lib/libQtGui.4.dylib @executable_path/../Frameworks/libQtGui.4.dylib csvimp
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib csvimp
-
-if ! [ -d "../plugins" ]; then
-  mkdir ../plugins
+if [ $# -lt 1 -o $# -gt 2 ] ; then
+  usage
+  exit 1
+elif [ $# -eq 1 ] ; then
+  APPROOT=$1
+  EXECNAME=`basename $APPROOT .app`
+elif [ $# -eq 2 ] ; then
+  APPROOT=$1
+  EXECNAME=$2
 fi
-cd ../plugins
 
-if ! [ -d "sqldrivers" ]; then
-  mkdir sqldrivers
+if ! [ -d "$APPROOT" ] ; then
+  echo "$PROG: $APPROOT does not exist so either rebuild or specify a .app directory"
+  exit 1
+elif ! [ -f "$APPROOT/Contents/MacOS/$EXECNAME" ] ; then
+  echo "$PROG: $APPROOT/Contents/MacOS/$EXECNAME does not exist so rebuild, "
+  echo "       specify a proper .app directory, or name the executable as well as the .app"
+  exit 1
 fi
-cd sqldrivers
 
-cp $QTDIR/plugins/sqldrivers/libqsqlpsql.dylib .
-install_name_tool -change $QTDIR/lib/libQtSql.4.dylib @executable_path/../Frameworks/libQtSql.4.dylib libqsqlpsql.dylib
-install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libqsqlpsql.dylib
-install_name_tool -change $PGDIR/lib/libpq.4.dylib @executable_path/../Frameworks/libpq.4.dylib libqsqlpsql.dylib
+cd $APPROOT                                                     || exit 1
+APPROOT=`pwd`
 
-cd ../..
+collectAndRenameLibs() {
+  if [ $# -ne 1 ] ; then
+    echo "$PROG collectAndRenameLibs() expected 1 args and got $#: $*"
+    return 1
+  fi
+  if expr "$1" : '\/' > /dev/null ; then
+    FILE="$1"
+  else
+    FILE="`pwd`/$1"
+  fi
 
-if ! [ -d "Resources" ]; then
-  mkdir Resources
-fi
-cd Resources
+  STARTDIR=`pwd`
+  NEWLOC="@executable_path/../Frameworks"
 
+  FRAMEWORKSDIR=$APPROOT/Contents/Frameworks
+  [ -d $FRAMEWORKSDIR ] || mkdir $FRAMEWORKSDIR                     || return 1
+  cd $FRAMEWORKSDIR                                                 || return 1
+
+  LIBSTORENAME=`otool -L $FILE | egrep "($QTDIR|$PGDIR)" |  awk '{print $1}'`
+  for TORENAME in $LIBSTORENAME ; do
+    BASETORENAME=`basename $TORENAME`
+    [ -e "$BASETORENAME" ] || cp "$TORENAME" .                      || return 1
+    install_name_tool -id $NEWLOC/$BASETORENAME $BASETORENAME       || return 1
+    install_name_tool -change $TORENAME $NEWLOC/$BASETORENAME $FILE || return 1
+  done
+
+  cd $STARTDIR                                                      || return 1
+  return 0
+}
+
+collectAndRenameLibs $APPROOT/Contents/MacOS/$EXECNAME              || exit 2
+
+[ -d $APPROOT/Contents/Resources ] || mkdir $APPROOT/Contents/Resources || exit 3
+cd $APPROOT/Contents/Resources                                  ||  exit 3
+# create a qt.conf file pointing to the plugins directory
 echo "[Paths]" > qt.conf
 echo "Prefix = .." >> qt.conf
+
+if $INCLIMAGEPLUGINS ; then
+  [ -d $APPROOT/Contents/plugins/imageformats ] || \
+    mkdir -p $APPROOT/Contents/plugins/imageformats                 || exit 2
+  TMPPLUGINS=`ls $QTDIR/plugins/imageformats/*.dylib | grep -v _debug`
+  cp $TMPPLUGINS $APPROOT/Contents/plugins/imageformats || exit 2
+fi
+
+if $INCLDBPLUGINS ; then
+  [ -d $APPROOT/Contents/plugins/sqldrivers ] || \
+    mkdir -p $APPROOT/Contents/plugins/sqldrivers                 || exit 2
+  TMPPLUGINS=`ls $QTDIR/plugins/sqldrivers/*.dylib | grep -v _debug`
+  cp $TMPPLUGINS $APPROOT/Contents/plugins/sqldrivers || exit 2
+fi
+
+if $INCLXTUPLEPLUGINS ; then
+  [ -d $APPROOT/Contents/plugins/designer ] || \
+    mkdir -p $APPROOT/Contents/plugins/designer                 || exit 2
+  cp $QTDIR/plugins/designer/libxtuplewidgets.dylib $APPROOT/Contents/plugins/designer || exit 2
+fi
+
+for PLUGIN in $APPROOT/Contents/plugins/*/*.dylib ; do
+  collectAndRenameLibs $PLUGIN                                  || exit 2
+done
+
+if $INCLASSISTANT ; then
+  cp -r $QTDIR/bin/Assistant_adp.app $APPROOT/Contents/Resources/Assistant_adp.app                || exit 3
+  collectAndRenameLibs $APPROOT/Contents/Resources/Assistant_adp.app/Contents/MacOS/Assistant_adp || exit 3
+  cd $APPROOT/Contents/Resources/Assistant_adp.app/Contents       || exit 3
+  ln -s ../../../Frameworks .                                     || exit 3
+  echo "[Paths]" > qt.conf
+  echo "Prefix = .." >> qt.conf
+fi
+
+while [ `otool -L $APPROOT/Contents/Frameworks/* | egrep "($QTDIR|$PGDIR)" | wc -l` -gt 0 ] ; do
+  for LIB in $APPROOT/Contents/Frameworks/* ; do
+    collectAndRenameLibs $LIB                || exit 4
+  done
+done
+
+exit 0
